# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  ntp:
    image: socheatsok78/chrony:dev
    environment:
      TZ: "UTC+0"
      LOGLEVEL: "0"
      NTP_SERVER_COUNT: "2"
      NTP_SERVER_1_ADDR: "pool.ntp.org"
      NTP_SERVER_1_NTS: "false"
      NTP_SERVER_2_ADDR: "time.cloudflare.com"
      NTP_SERVER_2_NTS: "true"
    ports:
      - mode: host
        target: 123
        published: 123
        protocol: udp
    networks:
      chrony-network:
    volumes:
      - type: tmpfs
        target: /etc/chrony
        tmpfs:
          mode: 1750
          size: 1e5
      - type: tmpfs
        target: /run/chrony
        tmpfs:
          mode: 1750
          size: 1e5
      - type: tmpfs
        target: /var/lib/chrony
        tmpfs:
          mode: 1750
          size: 1e5
    deploy:
      mode: global

networks:
  chrony-network:
