# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  chrony:
    image: socheatsok78/chrony:3.20
    environment:
      TZ: "UTC+0"
      LOGLEVEL: "0"
    ports:
      - mode: host
        target: 123
        published: 123
        protocol: udp
      - mode: host
        target: 9123
        published: 9123
        protocol: tcp
    cap_add:
      - IPC_LOCK
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
