#!/bin/sh
set -e

# Create the chrony run directory if it doesn't exist
mkdir -p /run/chrony

# confirm correct permissions on chrony run directory
chown -R chrony:chrony /run/chrony
chmod o-rx /run/chrony

# remove previous pid file if it exist
rm -f /run/chrony/chronyd.pid

# confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
	chown -R chrony:chrony /var/lib/chrony
fi
