#!/bin/sh
set -e

# create chrony run directory
mkdir -p /var/run/chrony

if [ -d /var/run/chrony ]; then
	# confirm correct permissions on chrony run directory
	chown -R chrony:chrony /var/run/chrony
	chmod o-rx /var/run/chrony
	# remove previous pid file if it exist
	rm -f /var/run/chrony/chronyd.pid
fi

# confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
	chown -R chrony:chrony /var/lib/chrony
fi
