#!/bin/sh
exec s6-setuidgid chrony \
	/bin/chrony_exporter \
		--web.listen-address=:9123 \
		--chrony.address=unix:///run/chrony/chronyd.sock \
		--collector.tracking \
		--collector.sources \
		--collector.serverstats \
		--collector.dns-lookups
